using System.Data.Common;
using Application.Abstractions.Data;
using Application.Abstractions.Messaging;
using Application.Abstractions.Services;
using Dapper;
using Domain.Staffs;
using SharedKernel;

namespace Application.Staffs.SyncStaffs;

internal sealed class SyncStaffsCommandHandler(
    IDbConnectionFactory dbConnectionFactory,
    ICsvService csvService)
    : ICommandHandler<SyncStaffsCommand>
{
    public async Task<Result> Handle(SyncStaffsCommand command, CancellationToken cancellationToken)
    {
        await using DbConnection connection = await dbConnectionFactory.OpenConnectionAsync();

        const string createSchemaSql = "CREATE SCHEMA IF NOT EXISTS bronze;";

        await connection.ExecuteAsync(createSchemaSql);

        const string createTableSql = $"""
            CREATE TABLE IF NOT EXISTS bronze.staffs (
                staff_id integer GENERATED BY DEFAULT AS IDENTITY,
                first_name character varying(50) NOT NULL,
                last_name character varying(50) NOT NULL,
                email character varying(255) NOT NULL,
                phone character varying(25),
                active boolean NOT NULL,
                store_id integer NOT NULL,
                manager_id integer,
                CONSTRAINT pk_staffs PRIMARY KEY (staff_id)
            );
            """;

        await connection.ExecuteAsync(createTableSql);

        List<Staff> staffs = csvService.ReadCsv<Staff>(command.FilePath);

        if (!staffs.Any())
        {
            return Result.Success();
        }

        using DbTransaction transaction = await connection.BeginTransactionAsync(cancellationToken);

        const string upsertSql = """
            INSERT INTO bronze.staffs (
                staff_id, 
                first_name, 
                last_name, 
                email, 
                phone, 
                active, 
                store_id, 
                manager_id
            ) 
            VALUES (
                @StaffId, 
                @FirstName, 
                @LastName, 
                @Email, 
                @Phone, 
                @Active, 
                @StoreId, 
                @ManagerId
            )
            ON CONFLICT (staff_id) 
            DO UPDATE SET 
                first_name = EXCLUDED.first_name,
                last_name = EXCLUDED.last_name,
                email = EXCLUDED.email,
                phone = EXCLUDED.phone,
                active = EXCLUDED.active,
                store_id = EXCLUDED.store_id,
                manager_id = EXCLUDED.manager_id
            """;

        await connection.ExecuteAsync(upsertSql, staffs, transaction: transaction);

        int[] staffIds = staffs.Select(b => b.StaffId).ToArray();

        const string deleteRemovedSql = """
            DELETE FROM bronze.staffs 
            WHERE staff_id != ALL(@StaffIds)
            """;

        await connection.ExecuteAsync(deleteRemovedSql, new { StaffIds = staffIds }, transaction: transaction);

        await transaction.CommitAsync(cancellationToken);

        return Result.Success();
    }
}
