CREATE TABLE bronze.customers (
    customer_id integer GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(250) NOT NULL,
    last_name character varying(250) NOT NULL,
    phone character varying(50),
    email character varying(500) NOT NULL,
    street text NOT NULL,
    city text NOT NULL,
    state text NOT NULL,
    zip_code text NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (customer_id)
);