CREATE TABLE bronze.products (
    product_id integer GENERATED BY DEFAULT AS IDENTITY,
    product_name character varying(500) NOT NULL,
    brand_id integer NOT NULL,
    category_id integer NOT NULL,
    model_year integer NOT NULL,
    list_price numeric NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (product_id),
    CONSTRAINT fk_products_brands_brand_id FOREIGN KEY (brand_id) REFERENCES bronze.brands (brand_id) ON DELETE CASCADE,
    CONSTRAINT fk_products_categories_category_id FOREIGN KEY (category_id) REFERENCES bronze.categories (category_id) ON DELETE CASCADE
);

CREATE INDEX ix_products_brand_id ON bronze.products (brand_id);
CREATE INDEX ix_products_category_id ON bronze.products (category_id);