CREATE TABLE bronze.stores (
    store_id integer GENERATED BY DEFAULT AS IDENTITY,
    store_name text NOT NULL,
    phone character varying(25) NOT NULL,
    email text NOT NULL,
    street text NOT NULL,
    city text NOT NULL,
    state text NOT NULL,
    zip_code text NOT NULL,
    CONSTRAINT pk_stores PRIMARY KEY (store_id)
);

CREATE UNIQUE INDEX ix_stores_email ON bronze.stores (email);