CREATE TABLE bronze.staffs (
    staff_id integer GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(250) NOT NULL,
    last_name character varying(250) NOT NULL,
    email text NOT NULL,
    phone character varying(25),
    active boolean NOT NULL,
    store_id integer NOT NULL,
    manager_id integer,
    CONSTRAINT pk_staffs PRIMARY KEY (staff_id),
    CONSTRAINT fk_staffs_staffs_manager_id FOREIGN KEY (manager_id) REFERENCES bronze.staffs (staff_id)
);

CREATE UNIQUE INDEX ix_staffs_email ON bronze.staffs (email);
CREATE INDEX ix_staffs_manager_id ON bronze.staffs (manager_id);