CREATE TABLE bronze.orders (
    order_id integer GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    order_status integer NOT NULL,
    order_date timestamp with time zone NOT NULL,
    required_date timestamp with time zone,
    shipped_date timestamp with time zone,
    store_id integer NOT NULL,
    staff_id integer NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_customers_customer_id FOREIGN KEY (customer_id) REFERENCES bronze.customers (customer_id) ON DELETE CASCADE,
    CONSTRAINT fk_orders_staffs_staff_id FOREIGN KEY (staff_id) REFERENCES bronze.staffs (staff_id) ON DELETE CASCADE,
    CONSTRAINT fk_orders_stores_store_id FOREIGN KEY (store_id) REFERENCES bronze.stores (store_id) ON DELETE CASCADE
);

CREATE INDEX ix_orders_customer_id ON bronze.orders (customer_id);
CREATE INDEX ix_orders_staff_id ON bronze.orders (staff_id);
CREATE INDEX ix_orders_store_id ON bronze.orders (store_id);