CREATE TABLE bronze.order_items (
    item_id integer GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    list_price numeric NOT NULL,
    discount numeric NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (item_id),
    CONSTRAINT fk_order_items_orders_order_id FOREIGN KEY (order_id) REFERENCES bronze.orders (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_products_product_id FOREIGN KEY (product_id) REFERENCES bronze.products (product_id) ON DELETE CASCADE
);

CREATE INDEX ix_order_items_order_id ON bronze.order_items (order_id);
CREATE INDEX ix_order_items_product_id ON bronze.order_items (product_id);