CREATE TABLE silver.dim_customers (
    customer_id integer GENERATED BY DEFAULT AS IDENTITY,
    first_name text NOT NULL,
    last_name text NOT NULL,
    phone text,
    email text NOT NULL,
    street text NOT NULL,
    city text NOT NULL,
    state text NOT NULL,
    zip_code text NOT NULL,
    CONSTRAINT pk_dim_customers PRIMARY KEY (customer_id)
);