CREATE TABLE silver.dim_products (
    product_id integer GENERATED BY DEFAULT AS IDENTITY,
    product_name text NOT NULL,
    brand_id integer NOT NULL,
    category_id integer NOT NULL,
    model_year integer NOT NULL,
    list_price numeric NOT NULL,
    CONSTRAINT pk_dim_products PRIMARY KEY (product_id)
);