CREATE TABLE silver.dim_stores (
    store_id integer GENERATED BY DEFAULT AS IDENTITY,
    store_name text NOT NULL,
    phone text NOT NULL,
    email text NOT NULL,
    street text NOT NULL,
    city text NOT NULL,
    state text NOT NULL,
    zip_code text NOT NULL,
    CONSTRAINT pk_dim_stores PRIMARY KEY (store_id)
);